"""Master parameters for GP-TARS V2 1000.

All linear dimensions are millimetres, torque values are N*m, and voltage is V.
Values marked as placeholders must not be used to release production hardware.
"""

PROJECT_NAME = "GP-TARS V2 1000"

# External reference
ROBOT_HEIGHT = 1000.0
SOURCE_HEIGHT_MEASURED = 250.3969610849432
SOURCE_WIDTH_MEASURED = 240.06000000001737
SOURCE_DEPTH_MEASURED = 65.070011622468
REFERENCE_SCALE_MEASURED = ROBOT_HEIGHT / SOURCE_HEIGHT_MEASURED
ROBOT_WIDTH_REFERENCE = SOURCE_WIDTH_MEASURED * REFERENCE_SCALE_MEASURED
ROBOT_DEPTH_REFERENCE = SOURCE_DEPTH_MEASURED * REFERENCE_SCALE_MEASURED

# Shell
SHELL_WALL = 3.0
SHELL_WALL_MIN = 2.5
SHELL_WALL_MAX = 4.0

# Structure
FRAME_PROFILE_SMALL = 20.0
FRAME_PROFILE_LARGE_X = 20.0
FRAME_PROFILE_LARGE_Y = 40.0
STRUCTURAL_MATERIAL = "6061-T6 aluminium"
PANEL_MATERIAL_OPTIONS = ("PETG", "ASA", "CF-reinforced filament")

# Shafts and bearings
MAIN_SHAFT_DIAMETER = 20.0
SECONDARY_SHAFT_DIAMETER = 12.0

# Actuator design targets. Do not freeze until load cases are calculated.
MAIN_ACTUATOR_DIAMETER_MIN = 80.0
MAIN_ACTUATOR_DIAMETER_MAX = 120.0
MAIN_ACTUATOR_LENGTH_MIN = 50.0
MAIN_ACTUATOR_LENGTH_MAX = 100.0
MAIN_ACTUATOR_CONTINUOUS_TORQUE_MIN = 60.0
MAIN_ACTUATOR_PEAK_TORQUE_INITIAL_MIN = 100.0
SECONDARY_ACTUATOR_TORQUE_MIN = 10.0
SECONDARY_ACTUATOR_TORQUE_MAX = 25.0

# Power and clearance
BATTERY_VOLTAGE = 24.0
GROUND_CLEARANCE_MIN = 10.0
GROUND_CLEARANCE_MAX = 25.0

# Replaceable equipment envelopes
MINI_PC_WIDTH = 220.0
MINI_PC_HEIGHT = 220.0
MINI_PC_DEPTH = 80.0

GPU_LENGTH = 300.0
GPU_HEIGHT = 130.0
GPU_WIDTH = 60.0

BATTERY_WIDTH = 300.0
BATTERY_DEPTH = 150.0
BATTERY_HEIGHT = 120.0

# Main actuator placeholders
ACTUATOR_MAIN_PLACEHOLDER_DIAMETER = 120.0
ACTUATOR_MAIN_PLACEHOLDER_LENGTH = 100.0
ACTUATOR_SECONDARY_PLACEHOLDER_DIAMETER = 70.0
ACTUATOR_SECONDARY_PLACEHOLDER_LENGTH = 70.0

# Cooling reservation options
FAN_SIZES = (80.0, 92.0, 120.0)

