"""Master parameters for GP-TARS V2 1000.

All linear dimensions are millimetres, torque values are N*m, and voltage is V.
Values marked as placeholders must not be used to release production hardware.
"""

PROJECT_NAME = "GP-TARS V2 1000"

# External reference
ROBOT_HEIGHT = 1000.0
SOURCE_HEIGHT_MEASURED = 250.3969610849432
SOURCE_WIDTH_MEASURED = 240.06000000001737
SOURCE_DEPTH_MEASURED = 65.070011622468
REFERENCE_SCALE_MEASURED = ROBOT_HEIGHT / SOURCE_HEIGHT_MEASURED
ROBOT_WIDTH_REFERENCE = SOURCE_WIDTH_MEASURED * REFERENCE_SCALE_MEASURED
ROBOT_DEPTH_REFERENCE = SOURCE_DEPTH_MEASURED * REFERENCE_SCALE_MEASURED

# Aluminium exterior. Thin formed sheet replaces printed cosmetic panels.
SHELL_WALL = 1.2
SHELL_WALL_MIN = 1.0
SHELL_WALL_MAX = 1.6
SHELL_MATERIAL = "5052-H32 aluminium sheet"
PANEL_EDGE_RETURN = 15.0
PANEL_LOCAL_DOUBLER = 2.0

# Structure
FRAME_PROFILE_SMALL = 20.0
FRAME_PROFILE_LARGE_X = 20.0
FRAME_PROFILE_LARGE_Y = 40.0
STRUCTURAL_MATERIAL = "6061-T6 aluminium"
FRAME_MATERIAL = "6061-T6 aluminium"
FRAME_JOINING = "TIG welded"
FRAME_SECTION_RAIL = "20 x 40 x 2.5 wall"
FRAME_SECTION_MEMBER = "20 x 20 x 2.0 wall"
FRAME_PARENT_YIELD_MPA = 276.0
FRAME_WELDED_YIELD_MPA = 145.0
FRAME_HAZ_EXTENT = 25.0
FRAME_FILLER = "4043 or 5356; 5356 for higher joint strength"
FRAME_JIG_REQUIRED = True
BEARING_BORES_MACHINED_AFTER_WELD = True
JOINT_BULKHEAD_MATERIAL = "6061-T6 aluminium plate"
JOINT_BULKHEAD_THICKNESS = 8.0
ACTUATOR_BRACKET_THICKNESS = 8.0
BATTERY_TRAY_MATERIAL = "5052-H32 aluminium sheet"
BATTERY_TRAY_THICKNESS = 3.0
ELECTRONICS_TRAY_MATERIAL = "5052-H32 aluminium sheet"
ELECTRONICS_TRAY_THICKNESS = 2.0

# Shafts and bearings
MAIN_SHAFT_DIAMETER = 20.0
SECONDARY_SHAFT_DIAMETER = 12.0

# Selected drive
ACTUATOR_MODEL = "CubeMars AK45-10 V3.0"
ACTUATOR_COUNT_SELECTED = 2
ACTUATOR_NOMINAL_V = 24.0
ACTUATOR_SUPPLY_VIA_BOOST = True
BOOST_INPUT_V = 12.8
BOOST_OUTPUT_V = 24.0
BOOST_COUNT = 2
BOOST_MODULE_RATING_W = 480.0
BOOST_MODULE_OUTPUT_A = 20.0
BOOST_MODULE_INPUT_A = 41.7
BOOST_TOTAL_INPUT_A = 83.3
BOOST_INGRESS = "IP68"
BOOST_CONTINUOUS_W = 400.0
BOOST_PEAK_W = 800.0
BOOST_MODULE_LENGTH = 128.0
BOOST_MODULE_WIDTH = 98.0
BOOST_MODULE_HEIGHT = 40.0
BOOST_MODULE_MASS_KG = 0.6
BOOST_RAILS_INDEPENDENT = True
BOOST_BULK_CAPACITANCE_REQUIRED = True
BRAKE_CHOPPER_REQUIRED = True
BRAKE_CHOPPER_COUNT = 2
BRAKE_CHOPPER_NOTE = "Gait is a controlled fall; a unidirectional boost gives regeneration no path back"
ACTUATOR_RATED_TORQUE = 2.5
ACTUATOR_PEAK_TORQUE = 7.0
ACTUATOR_INTERNAL_RATIO = 10.0
ACTUATOR_DIAMETER = 53.0
ACTUATOR_LENGTH = 43.0
ACTUATOR_MASS_KG = 0.26
REDUCTION_STAGE2_RATIO = 32.0
REDUCTION_TOTAL_RATIO = ACTUATOR_INTERNAL_RATIO * REDUCTION_STAGE2_RATIO
REDUCTION_STAGE2_TYPE = "Cycloidal or two-stage planetary; partially backdrivable"
REDUCTION_STAGE2_EFFICIENCY = 0.85
REDUCTION_STAGE2_DIAMETER = 90.0
REDUCTION_STAGE2_LENGTH = 50.0
JOINT_CONTINUOUS_TORQUE = ACTUATOR_RATED_TORQUE * REDUCTION_STAGE2_RATIO
JOINT_PEAK_TORQUE = ACTUATOR_PEAK_TORQUE * REDUCTION_STAGE2_RATIO
MAIN_ACTUATOR_CONTINUOUS_TORQUE_MIN = 60.0
MAIN_ACTUATOR_PEAK_TORQUE_INITIAL_MIN = 100.0
CAN_HUB_MODEL = "CubeMars Rubik Link V3.0"
CAN_HUB_ROLE = "Bench bring-up only; flight CAN runs from the deterministic MCU"

# Power and clearance
BATTERY_VOLTAGE = 12.8
CHASSIS_GROUND_CLEARANCE = 25.0
BODY_DROP_AT_WORKING_SPLAY = 12.7
GROUND_CLEARANCE_MIN = 10.0
GROUND_CLEARANCE_MAX = 25.0

# Installed compute
MINI_PC_MODEL = "MINISFORUM AI X1 Pro-370"
MINI_PC_WIDTH = 195.0
MINI_PC_HEIGHT = 195.0
MINI_PC_DEPTH = 47.5
MINI_PC_MASS_KG = 1.5
MINI_PC_ORIENTATION = "Edge-on; board plane parallel to the side panels"
MINI_PC_KEEP_OUT_WIDTH = 100.0
MINI_PC_KEEP_OUT_HEIGHT = 225.0
MINI_PC_KEEP_OUT_DEPTH = 210.0
MINI_PC_POWER_INTERNAL_W = 134.9
MINI_PC_USB4_PD_INPUT_W = 100.0
MINI_PC_USB4_PD_INPUT_V = 20.0

# Future external accelerator
GPU_REQUIRED = False
GPU_PHASE = "Phase 2 optional accelerator"
GPU_ROLE = "Heavier CUDA LLM / vision inference"
GPU_VENDOR_TARGET = "NVIDIA"
GPU_MODEL = "NVIDIA RTX 2000 Ada Generation"
GPU_VRAM_GB = 16
GPU_TDP_W = 70.0
GPU_AUX_POWER_CONNECTOR = False
GPU_ORIENTATION = "Vertical, single slot; the 168 mm card length runs up the body"
GPU_LENGTH = 168.0
GPU_HEIGHT = 69.0
GPU_WIDTH = 17.6
GPU_LATERAL_DEMAND = 90.0
GPU_LINK = "OCuLink PCIe 4.0 x4"
GPU_POWER_SOURCE = "Slot power only, 70 W; no separate GPU PSU required"
GPU_PSU_ENVELOPE = None

BATTERY_WIDTH = 200.0
BATTERY_HEIGHT = 150.0
BATTERY_DEPTH = 180.0
ACTUATOR_HIP_PLACEHOLDER_DIAMETER = 120.0
ACTUATOR_HIP_PLACEHOLDER_LENGTH = 100.0
ACTUATOR_KNEE_PLACEHOLDER_DIAMETER = 70.0
ACTUATOR_KNEE_PLACEHOLDER_LENGTH = 70.0
FAN_SIZES = (80.0, 92.0, 120.0)

# Reconstructed articulation axes
SOURCE_Y_MIN = -10.366961
AXLE_LOWER_MAIN_HEIGHT_SOURCE = 152.951961
AXLE_LOWER_SECONDARY_HEIGHT_SOURCE = 196.826961
AXLE_UPPER_MAIN_HEIGHT_SOURCE = 209.826961
AXLE_UPPER_SECONDARY_HEIGHT_SOURCE = 222.826961
AXLE_LOWER_MAIN_Y = AXLE_LOWER_MAIN_HEIGHT_SOURCE * REFERENCE_SCALE_MEASURED
AXLE_LOWER_SECONDARY_Y = AXLE_LOWER_SECONDARY_HEIGHT_SOURCE * REFERENCE_SCALE_MEASURED
AXLE_UPPER_MAIN_Y = AXLE_UPPER_MAIN_HEIGHT_SOURCE * REFERENCE_SCALE_MEASURED
AXLE_UPPER_SECONDARY_Y = AXLE_UPPER_SECONDARY_HEIGHT_SOURCE * REFERENCE_SCALE_MEASURED

ROBOT_WIDTH_SOURCE_SCALED = 958.718
ROBOT_WIDTH = 480.0
SLAB_COUNT = 4
SLAB_WIDTH = 120.0
CENTRAL_CHASSIS_WIDTH = 240.0
CENTRAL_CHASSIS_WIDTH_SOURCE = 133.232
CENTRAL_CHASSIS_WIDTH_SCALED = CENTRAL_CHASSIS_WIDTH_SOURCE * REFERENCE_SCALE_MEASURED
UPPER_LID_FRONT_WIDTH = CENTRAL_CHASSIS_WIDTH
UPPER_LID_FRONT_HEIGHT = ROBOT_HEIGHT - AXLE_UPPER_SECONDARY_Y
ARM_KNEE_RATIO = 0.5
AXLE_KNEE_Y = AXLE_LOWER_MAIN_Y * ARM_KNEE_RATIO
ARM_CLEARANCE = 4.0
ARM_JOINT_GAP = 2.0
ARM_SLAB_WIDTH = 116.0

DECAL_WORDMARK_COLOUR = "#d97b19 orange"
DECAL_WORDMARK_ORIENTATION = "Rotated 90 degrees, reading up the panel"
DECAL_WORDMARK_SIZE = "52 x 250"
DECAL_WORDMARK_ORIGIN_Y = 350.0

# Upper face cassette: camera above display, microphone below display.
# Camera/microphone mechanical envelopes are reservations only until purchased
# hardware is measured or authoritative mechanical drawings are locked.
SENSOR_CASSETTE_PRESENT = True
SENSOR_CASSETTE_ORDER_TOP_TO_BOTTOM = ("OAK-D Pro W USB", "Display", "ReSpeaker XVF3800 under the lid")
CAMERA_MODEL = "Luxonis OAK-D Pro W USB"
CAMERA_LOCATION = "Upper front face, centred above display"
CAMERA_INTERFACE = "USB 3"
CAMERA_WIDTH_RESERVATION = 160.0
CAMERA_HEIGHT_RESERVATION = 45.0
CAMERA_DEPTH_RESERVATION = 45.0
CAMERA_TOP_MARGIN = 10.0
CAMERA_SERVICE_CLEARANCE = 10.0
CAMERA_DIMENSIONS_STATUS = "RESERVATION - verify exact purchased SKU before cutting panel"
MIC_MODEL = "Seeed Studio ReSpeaker XVF3800 USB 4-Mic Array"
MIC_LOCATION = "Under the top lid, behind the camera; the front face cannot hold it"
MIC_INTERFACE = "USB"
MIC_WIDTH_RESERVATION = 90.0
MIC_HEIGHT_RESERVATION = 35.0
MIC_DEPTH_RESERVATION = 20.0
MIC_SERVICE_CLEARANCE = 10.0
MIC_VIBRATION_ISOLATION_REQUIRED = True
MIC_DIMENSIONS_STATUS = "RESERVATION - verify purchased hardware before cutting panel"

DISPLAY_PRESENT = True
DISPLAY_LOCATION = "Upper front face, between camera and microphone"
DISPLAY_CLASS = "14 inch portrait TFT-LED, 12 V"
DISPLAY_ACTIVE_WIDTH = 174.0
DISPLAY_ACTIVE_HEIGHT = 310.0
# Lowered from 655 to clear the camera above it. See the cassette fit note
# below: the camera occupies 945-990 mm, so the 328 mm display module has to
# finish by 944. 625 is what that leaves.
DISPLAY_ORIGIN_Y = 625.0
DISPLAY_MARGIN_PER_SIDE = 33.0
DISPLAY_CENTRE_Y = 780.0
UPPER_CHASSIS_ASSUMED_RIGID = True
DISPLAY_DEPTH_RESERVATION = 35.0
DISPLAY_MODULE_WIDTH = 215.0
DISPLAY_MODULE_HEIGHT = 328.0
DISPLAY_MODULE_THICKNESS = 28.0
DISPLAY_MODULE_CLEARANCE_PER_SIDE = 11.3
DISPLAY_MODULE_TOLERANCE_STATED = 30.0
DISPLAY_STACK_DEPTH = 33.2
DISPLAY_SUPPLY_V = 12.0
DISPLAY_POWER_W = 18.0
DISPLAY_AUDIO_W = 2.0
DISPLAY_SPEAKERS = "Two 32 mm, driven over HDMI audio"
DISPLAY_COVER_THICKNESS = 2.0
DISPLAY_DOUBLER_THICKNESS = 2.0
DISPLAY_INTERFACE = "HDMI from the mini PC; both sit in the lower chassis"
DISPLAY_COVER_MATERIAL = "Chemically strengthened glass or bonded polycarbonate"
DISPLAY_MASS_ESTIMATE_KG = 0.8
DISPLAY_LINK = "Direct HDMI from the mini PC; nothing crosses a moving joint"
PANEL_HIP_BREAK_GAP = 6.0

# Geometry for the cassette above. The selections and reservations are recorded
# with the sensor block higher up; these are the positions the CAD builds from.
#
# The stack as first written does not fit. Camera 45 + top margin 10, display
# module 328 and microphone 35 need 418 mm of upper front face, and the face
# between the hip break and the lid is 384.2 mm. That is 33.8 mm over, and still
# 23.8 mm over with every margin set to zero. So the microphones come off the
# front face and mount under the top lid, which fits, puts them further from the
# display's heat, and gives a far-field array a better acoustic position than a
# panel that drums. SENSOR_CASSETTE_ORDER_TOP_TO_BOTTOM is updated to match.
SENSOR_CASSETTE_ORDER_ACTUAL = ("OAK-D Pro W USB", "Display", "ReSpeaker XVF3800 on the top lid")
SENSOR_CASSETTE_FIT_NOTE = "Front-face stack was 33.8 mm over; microphones relocated to the lid"
SENSOR_PLATE_THICKNESS = 3.0
SENSOR_CASSETTE_REMOVABLE = True

# Camera sits hard against the top margin, and the display drops to clear it.
CAMERA_CENTRE_Y = ROBOT_HEIGHT - CAMERA_TOP_MARGIN - CAMERA_HEIGHT_RESERVATION / 2
CAMERA_EYELINE_Y = CAMERA_CENTRE_Y
CAMERA_APERTURE_WIDTH = 110.0
CAMERA_APERTURE_HEIGHT = 26.0
CAMERA_PROVIDES = "RGB and stereo depth in one module, covering both cameras the specification lists separately"

# Under the lid, behind the camera, ported up through it.
MIC_MOUNTING = "Under the top lid, behind the camera"
MIC_ARRAY_CHANNELS = 4
MIC_LID_Z0 = 30.0
MIC_PORT_DIAMETER = 5.0

# The aperture doubler's flange drops from 18 mm to 10 mm. At 18 it reaches
# below the hip break once the display moves down; 10 mm is still a normal
# flange around a display cut-out.
DISPLAY_DOUBLER_FLANGE = 10.0

# Speakers stay the display module's own pair, DISPLAY_SPEAKERS. Reserving
# separate drivers would hold space for hardware the robot already carries.
SPEAKERS_SEPARATE_REQUIRED = False

TOF_COUNT = 2
TOF_MODULE_SIZE = 26.0
TOF_MODULE_DEPTH = 18.0
TOF_CENTRE_Y = 330.0
TOF_SPACING_X = 150.0
TOF_PURPOSE = "Step edges and near obstacles below the camera's field of view"

LIDAR_OPTIONAL = True
LIDAR_DIAMETER = 72.0
LIDAR_HEIGHT = 42.0
LIDAR_CANDIDATE = "RPLIDAR C1 class, mounted on the top lid when fitted"
# A 360 degree scanner must stand proud of the lid, so fitting one takes the
# robot above its 1000 mm envelope. Only the mounting pad is modelled.
LIDAR_FITTED_HEIGHT_Y = ROBOT_HEIGHT + LIDAR_HEIGHT

FOOT_CONTACT_SENSOR_PER_FOOT = 1
FOOT_CONTACT_SENSOR_SIZE = 24.0
FOOT_CONTACT_SENSOR_PURPOSE = "Ground-contact confirmation for the gait state machine"

SENSOR_MASS_ESTIMATE_KG = 0.25

# Compute stack. Units here are GB and counts, not millimetres.
HOST_OS = "Ubuntu 24.04 LTS"
ROS_DISTRO = "Jazzy"
CONTAINER_COUNT = 13
SYSTEM_RAM_GB = 64
SYSTEM_RAM_CONFIG = "2 x 32 GB DDR5-5600 SO-DIMM"
GPU_VRAM_MIN_GB = 16
GPU_VRAM_PREFERRED_GB = 24
NVME_SLOTS_AVAILABLE = 3
NVME_SYSTEM_GB = 4000
NVME_DATA_GB = 0

# Power budget
POWER_MODE_SLEEP_W = 8.0
POWER_MODE_ATTENTIVE_W = 39.0
POWER_MODE_CONVERSATION_W = 160.0
POWER_MODE_WALKING_W = 300.0
POWER_PEAK_OVERLAP_W = 460.0
POWER_PEAK_CURRENT_A = 36.0
GPU_POWER_GATED = True
GPU_GATING_METHOD = "Driver runtime suspend; hard isolation only in deep sleep"
BATTERY_USABLE_FRACTION = 0.9
BATTERY_CHEMISTRY = "LiFePO4"
BATTERY_MODEL = "WattCycle 12.8 V 100 Ah Mini LiFePO4"
BATTERY_ENERGY_WH = 1280.0
BATTERY_CAPACITY_AH = 100.0
ACTUATOR_BRAKES_REQUIRED = True

FRAME_RAIL_OUTBOARD_X = 118.8
FRAME_CLEAR_SPAN = 197.6

# Gait
GAIT_TYPE = "Compass walker, sagittal plane"
GAIT_DOF = 2
LIMB_RIGID = True
LEG_LENGTH = AXLE_LOWER_MAIN_Y
GAIT_SPLAY_HALF_ANGLE_DEG = 20.0
GAIT_STEP_LENGTH = 418.0
GAIT_SWING_TIME_S = 1.16
GAIT_SPEED_MS = 0.36
JOINT_ANGULAR_VELOCITY_RAD_S = 0.6
FOOT_ROCKER_RADIUS = 400.0
CENTRE_OF_MASS_HEIGHT_EST = 381.0
FOOT_HEIGHT = 80.0
FOOT_PAD_THICKNESS = 6.0
FOOT_SHOE_WALL = 3.0
FOOT_SHOE_MATERIAL = "6061-T6 aluminium"
FOOT_PAD_MATERIAL = "Elastomer contact pad, replaceable"
FOOT_SWING_CLEARANCE = 12.7
FOOT_ROCKER_SAGITTA = 21.7

# Charge and support dock
DOCK_PRESENT = True
DOCK_AUTONOMOUS_DOCKING = False
DOCK_CHARGE_CURRENT_A = 30.0
DOCK_CHARGE_POWER_W = 384.0
DOCK_CHARGE_TIME_H = 3.3
DOCK_CONTACT_TYPE = "Blade or brush, 30 A rated; pogo pins will not carry it"
DOCK_INTERLOCK = "Detect pin closes the contactor only when seated"
DOCK_CONTACT_HEIGHT_Y = 470.0
DOCK_GANTRY_HEIGHT = 1400.0
DOCK_SERVES = "Charging, fall-arrest during motion testing, mains for the GPU"
